### ISSUE TITLE
[fs.op.funcs] has 39 immediately-nested subclauses

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/draft#1849]
And most of the subclauses describe just one function, or two at best.

Ideas for more structure:
- Introduce subclauses "file properties" (exists, is_directory etc.), "modifiers" (rename, copy), "path operations" (canonical etc.), "others"
- Compactify the description of is_blah; the only difference between these functions is the file_status::type() result value that is checked.

**Comment by jensmaurer** [comment]
Editorial Meeting Consensus: We should have more structure here. Add categories.

is_empty has source code as prose text.

**Comment by AlisdairM** [comment]
It looks like this has been resolved, although I have not tracked down the PR that fixed it.

**Comment by jensmaurer** [comment]
This is not resolved; [fs.op.funcs] nowadays has 40 immediately-nested subclauses.

**Comment by AlisdairM** [comment]
My mistake --- I was looking at paragraph numbers, not subclauses.

Does the POSIX standard provide any guidance here, subdividing its own specification?
Or is this a categorization we should invent for ourselves?

Would such categorization still be in scope for C++26, or should we add this to the C++29 backlog?

**Comment by AlisdairM** [comment]
And as I was looking into this anyway, here is my personal and arbitrary attempt to subcategorize this clause:

### [fs.op.funcs]{Filesystem operation functions}

#### [fs.op.funcs.general]{General}

#### Filename queries

[fs.op.absolute]{Absolute}
[fs.op.canonical]{Canonical}
[fs.op.equivalent]{Equivalent}
[fs.op.proximate]{Proximate}
[fs.op.read.symlink]{Read symlink}
[fs.op.relative]{Relative}
[fs.op.weakly.canonical]{Weakly canonical}


##### File Categorization

[fs.op.is.block.file]{Is block file}
[fs.op.is.char.file]{Is character file}
[fs.op.is.directory]{Is directory}
[fs.op.is.empty]{Is empty}
[fs.op.is.fifo]{Is fifo}
[fs.op.is.other]{Is other}
[fs.op.is.regular.file]{Is regular file}
[fs.op.is.socket]{Is socket}
[fs.op.is.symlink]{Is symlink}


##### File properties

[fs.op.exists]{Exists}
[fs.op.file.size]{File size}
[fs.op.hard.lk.ct]{Hard link count}
[fs.op.last.write.time]{Last write time}
[fs.op.permissions]{Permissions}
[fs.op.status]{Status}
[fs.op.status.known]{Status known}
[fs.op.symlink.status]{Symlink status}

#### File creation

[fs.op.create.directories]{Create directories}
[fs.op.create.directory]{Create directory}
[fs.op.create.dir.symlk]{Create directory symlink}
[fs.op.create.hard.lk]{Create hard link}
[fs.op.create.symlink]{Create symlink}

#### File Manipulation

[fs.op.copy]{Copy}
[fs.op.copy.file]{Copy file}
[fs.op.copy.symlink]{Copy symlink}
[fs.op.remove]{Remove}
[fs.op.remove.all]{Remove all}
[fs.op.rename]{Rename}


#### Other

[fs.op.current.path]{Current path}
[fs.op.resize.file]{Resize file}
[fs.op.space]{Space}
[fs.op.temp.dir.path]{Temporary directory path}


I could easily imagine a different approach, such a breaking down by what is the primary subject of the function --- directories, symlinks/hardlinks, general-purpose files, etc.
