### ISSUE TITLE
what is the single code unit for a ordinary character literal

### ISSUE THREAD

**Issue by xmh0511** [cplusplus/draft#4517]
As the special rules specified in [lex.ccon]#1, that is:  
>A non-encodable character literal is a character-literal whose c-char-sequence consists of a single c-char that is not a numeric-escape-sequence and that specifies a character that either lacks representation in the literal's associated character encoding or that cannot be encoded as **a single code unit**.   

The Unicode standard specifies how large a **code unit** for UTF8, UTF16, and UTF32 respectively.  Which has a similar meaning as stated in [wiki Character_encoding](https://en.wikipedia.org/wiki/Character_encoding#Terminology).  However, it does not state how large the `code unit` for the encoding of the execution (wide-)character set.  So, in this case, how to determine whether a code point value for a character can be encoded as a single code unit in an ordinary (wide-)character literal?

Is it a good idea to change the wording "cannot be encoded as a single code unit" to "cannot be represented by an object with the type of the corresponding kind of character-literal"?

**Comment by jensmaurer** [comment]
I think [basic.fundamental] p7 and p8 try to establish the relationship between the type and code unit, but this could certainly be clearer.

**Comment by xmh0511** [comment]
> I think [basic.fundamental] p7 and p8 try to establish the relationship between the type and code unit, but this could certainly be clearer.

Although p7 states 
>The values of type char can represent distinct codes for all members of the implementation's basic character set. 

However, here is unclear that whether the wording "implementation's basic character set" refers to "basic source character set " or "basic execution character set". Presumably, it refers to the latter.  But, as stated in [[lex.charset#3]](https://eel.is/c++draft/lex.charset#3). **Execution character set** is a **superset** of a `basic execution character set`.  

As the [lex.ccon#tab:lex.ccon.literal](https://eel.is/c++draft/lex.ccon#tab:lex.ccon.literal) indicates, we don't know whether an element in the **absolute complement set** of **basic execution character set** can be encoded in a char object. After all, the standard does not specify how to encode an execution character set except that it specifies the value 0 for the null character.

**Comment by jensmaurer** [comment]
This is being addressed by P2314 Character sets and encodings cplusplus/papers#998.

**Comment by frederick-vs-ja** [comment]
This seems covered by CWG2779.

**Comment by AlisdairM** [comment]
Note that [P2314](https://wg21.link/p2314) landed at the St Louis meeting, July 2024.

The Core issue remains.
